install:
  - git submodule update --init --recursive
  
before_build:
  - nuget restore SpecFlow.Allure.sln

build_script: 
  - msbuild SpecFlow.Allure.sln /p:Configuration=Debug /t:Rebuild
  
test_script:
  - nunit3-console SpecFlow.Allure.Tests/bin/Debug/SpecFlow.Allure.Tests.dll
